on:
  workflow_call:
    inputs:
      username:
        description: 'Username'
        default: 'developerRSquared'
        required: false
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Run a one-line script
        run: echo Hello, world! ${{ inputs.username }}
