on:
  workflow_call:
    inputs:
      username:
        description: 'Username'
        default: 'developerRSquared'
        required: false
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world! ${{ inputs.username }}

  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
