name: Reusable Build

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
    branches:
      - main

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  do-it:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!
