name: Template

on:
  workflow_call:
    inputs:
      username:
        description: 'Username'
        default: 'developerRSquared'
        required: false
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
