name: Python Package Publish Template

on:
  workflow_call:
    inputs:
      pypi_url:
        description: 'URL for PyPI'
        default: 'https://pypi.org/'
        required: true
        type: string
      should_upload_coverage_to_codecov:
        description: 'Should upload coverage to Codecov?'
        default: false
        required: true
        type: boolean
      should_dry_run_publish_to_test_pypi:
        description: 'Should dry run publish to TestPyPI?'
        default: false
        required: true
        type: boolean
      should_publish_to_test_pypi:
        description: 'Should publish to TestPyPI?'
        default: false
        required: true
        type: boolean
    secrets:
      pypi_token:
        description: 'Token for PyPI'
        required: true
      codecov_token:
        description: 'Token for Codecov'
        required: false

jobs:
  publish:
    name: Publish

    runs-on: ubuntu-latest

    environment:
      name: TestPyPI
      url: ${{ inputs.pypi_url }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Get full Python version
        id: full-python-version
        run: echo ::set-output name=version::$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info))")

      - name: Install poetry 1.1.12
        uses: snok/install-poetry@v1
        with:
          version: 1.1.12

      - name: Configure poetry
        run: poetry config virtualenvs.in-project true

      - name: Set up cache
        uses: actions/cache@v2
        id: cache
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Ensure cache is healthy
        if: steps.cache.outputs.cache-hit == 'true'
        run: timeout 10s poetry run pip --version || rm -rf .venv

      - name: Install dependencies
        run: poetry install

      - name: Run tests (pytest)
        run: poetry run python -m pytest -c $(pwd)/pyproject.toml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        if: ${{ inputs.should_upload_coverage_to_codecov }}
        with:
          fail_ci_if_error: true
          token: ${{ secrets.codecov_token }}

      - name: Build project for distribution
        run: poetry build

      - name: Publish to Test PyPI (dry run)
        if: ${{ inputs.should_dry_run_publish_to_test_pypi }}
        env:
          POETRY_REPOSITORIES_TESTPYPI_URL: https://test.pypi.org/legacy/
          POETRY_HTTP_BASIC_TESTPYPI_USERNAME: __token__
          POETRY_HTTP_BASIC_TESTPYPI_PASSWORD: ${{ secrets.pypi_token }}
        run: poetry publish --dry-run --repository testpypi

      - name: Publish to Test PyPI
        if: ${{ inputs.should_publish_to_test_pypi }}
        env:
          POETRY_REPOSITORIES_TESTPYPI_URL: https://test.pypi.org/legacy/
          POETRY_HTTP_BASIC_TESTPYPI_USERNAME: __token__
          POETRY_HTTP_BASIC_TESTPYPI_PASSWORD: ${{ secrets.pypi_token }}
        run: poetry publish --repository testpypi
